### ISSUE TITLE
integration with mobile: android & iOS - DL model deployment and p2p integration

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#10]
see also 
- [PySyft](https://github.com/OpenMined/PySyft) 
- [iOS coreML](https://developer.apple.com/documentation/coreml)
- [ONNX](https://onnx.ai/)

inference still better supported than training currently...

**Comment by ykivva** [comment]
Link below looks like something what can be used:
https://developer.android.com/training/connect-devices-wirelessly/wifi-direct

**Comment by martinjaggi** [comment]
for the js case, we agreed we should look into https://github.com/OpenMined/syft.js/  and see if the deep net parts can be ported. any volunteers?

**Comment by martinjaggi** [comment]
i'll close this for now, as our [mobile prototype](https://github.com/epfml/DeAI/tree/master/mobile-browser-based-version) is ready (for now going browser-based with simpler peer.js for communication backend, and TF.js for the neural nets)
