### ISSUE TITLE
Create one peer.js server per task

### ISSUE THREAD

**Issue by giordano-lucas** [epfml/DeAI#131]
# Description  

At the moment, all tasks use the same `peer.js` sever and, therefore, the same topology. To improve flexibility, we need to create a separate `peer.js` for each of them. 

# Proposed Solution

1. Make `communication_manager.js` task-dependent (pass the task as an argument to the constructor). We can update the path from `/deai` to `/deai/<taskId>` in the peer-creation process.
2. In `run_server.js`, we create one `ExpressPeerServer` per task and update the routing accordingly.

> ⚠️ The code in `run_server.js` needs to be cleaned first (remove topologies and other stuff not used anymore). I will create a separate pull request for that.

**Comment by clicepfl** [comment]
I think this is linked to #94
