### ISSUE TITLE
Make the end of training more explicit

### ISSUE THREAD

**Issue by laurislopata** [epfml/DeAI#134]
At the moment, when the training of the model is finished only a small popup appears at the bottom of the screen. A user could easily miss it, it would be good to add "Training finished" or something similar at the end of the communication log for example.

**Comment by martinjaggi** [comment]
yes it's a bit unclear to the user how many epochs will be trained. is that value defined in the task definition currently?

**Comment by s314cy** [comment]
> yes it's a bit unclear to the user how many epochs will be trained. is that value defined in the task definition currently?

yes the number of epochs is defined in the json file served by the centralized server, and btw this issue is fixed in #144 by adding a single line in the new `/helpers/communication/client.js` superclass (see commit referenced above)
