### ISSUE TITLE
data upload: small improvements / some data sanity checks 

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#37]
we could add a few more small checks and error messages,
now in the MNIST example it throws some NaN error if not all image types are present. and in the Titanic one complains about the last column missing sometimes even when it's not (maybe doesn't like newline at the end of a csv file?). works nicely with the provided titanic data though

add status message in UI once data has been successfully loaded. and another one once training is successfully started

**Comment by martinjaggi** [comment]
has been resolved i think?

**Comment by PaulMansat** [comment]
Yes, now the user is notified when training starts and ends. 
And the issue regarding the header check is resolved. 
For images, I think Marcel solved it.
