### ISSUE TITLE
task list server (and p2p participants list) always running for easier use

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#38]
let's have the helper server running on a small instance in the gcloud so the app can always be easily used (even with peer.js).

not sure how we want to keep the participants list updated at the moment (one or two? maybe one on gcloud?)

- [x] and if p2p is not available, show a message that the training did a fall-back to local training (training alone) instead

**Comment by PaulMansat** [comment]
To run the app on Gcloud, do we have credentials? 
I thought that we were keeping the app local for the development stage.

**Comment by s314cy** [comment]
this issue was fixed some time ago and the required features are already present on the production version of DeAI :)
