### ISSUE TITLE
p2p dummy communication prototype

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#5]
Using https://libp2p.io/ or a simplified backend, build a first prototype which connects nodes and allows exchange of dummy arrays (tensors) between nodes.

See #3 for discussion on libp2p

**Comment by ykivva** [comment]
Link below looks like something what can be used:
https://developer.android.com/training/connect-devices-wirelessly/wifi-direct

**Comment by martinjaggi** [comment]
thanks @ykivva ! based on the nice discussion we had on friday i'm also adding the suggestions by others for potential backends. we'll go with whichever one would make it easiest to get a first prototype up and running:

- python standalone @lfbarba , such as #3 and maybe there are even simpler ones?
- browser-based javascript options via webRTC #12 
- android (such as @ykivva 's comment above) or iOS based ones?

what do others think?

**Comment by martinjaggi** [comment]
closing this for now, as we have it both for desktop (python) and mobile/browser
