### ISSUE TITLE
Fix: Port numbers are hardcoded

### ISSUE THREAD

**Issue by MarcelTorne** [epfml/DeAI#73]
At this moment, port numbers are being hardcoded in the `communication_manager` file. Inside this file we should always use the portNbr attribute passed in the constructor, and then each task should pass its corresponding port number to the `communication_manager`.

**Comment by PaulMansat** [comment]
This is taken care of in the new routing with the new vue memory management issue. It should be a separate issue, but I solved the problem directly when working in the new routine architecture to ensure that no problems could come from sharing communication's manager.
