### ISSUE TITLE
Allow task owner to set a password for joining a task

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#82]
For allowing joint training within a smaller set of trusted participants only (in addition to public tasks)

- [ ] Add an optional password hash to the task description. 
- [ ] If present, new users will be asked the password before being able to join a task (like "joining this task is password restricted").
- [ ] Add this to the documentation of how users can create a new task.

This functionality basically recovers federated learning as a special case. This is not giving the same security standard as a full PKI, and is not a replacement for a selection mechanism for helpful clients (as opposed to Byzantine ones), but is a start (see the same discussions in federated learning literature)

**Comment by martinjaggi** [comment]
we can close this i think? except maybe should add the feature to the documentation somewhere?

**Comment by martinjaggi** [comment]
and remove from mnist again

**Comment by martinjaggi** [comment]
ping

**Comment by mmilenkoski** [comment]
Closing the issue since the functionality is now implemented.

We can allow the user to enter a password when they create a task through the form in the UI. 

I also removed the password protection for Titanic already.
