### ISSUE TITLE
.csv column reassignment UI

### ISSUE THREAD

**Issue by martinjaggi** [epfml/DeAI#92]
small simplification suggestion (need only  `id ← edit field`)

should look like (or even on same line):
<img width="145" alt="Screen Shot 2021-06-22 at 00 23 03" src="https://user-images.githubusercontent.com/4621895/122835108-14ed1d80-d2f0-11eb-9083-87c8bcf5c7b2.png">

current look:
<img width="251" alt="Screen Shot 2021-06-22 at 00 20 00" src="https://user-images.githubusercontent.com/4621895/122835115-17e80e00-d2f0-11eb-98ba-5a3c140c12fb.png">

**Comment by lippoldt** [comment]
@martinjaggi @PaulMansat  I propose to slightly change the style to either 3 line arrangement or one line, which one do you prefer? 
<img width="320" alt="Screenshot 2021-06-22 at 14 08 48" src="https://user-images.githubusercontent.com/12049501/122922688-325bcf00-d364-11eb-9d75-bfd271060dcb.png">
<img width="336" alt="Screenshot 2021-06-22 at 14 14 21" src="https://user-images.githubusercontent.com/12049501/122922693-32f46580-d364-11eb-9c59-ad2a2425a22d.png">
Adding another line will integrate more smoothly into the structure, for a one liner I would also change some of the parent div's (i.e. simplify overall structure)

**Comment by martinjaggi** [comment]
whichever you prefer.
arrow should point from source text field to target td

**Comment by mmilenkoski** [comment]
closing this because it was resolved in #93
