### ISSUE TITLE
Host each task as a separate Google App Engine service

### ISSUE THREAD

**Issue by mmilenkoski** [epfml/DeAI#94]
Now that we use Google App Engine (GAE) to host our app, we can no longer use different ports for different tasks since we access the server through a domain. Instead, we can host each task as a separate service within our app. In this way, each task can have its separate domain. The potential benefit is that we do not have to interrupt existing tasks to add a new task. I haven't tried this yet. Let me know what you think and whether you have any alternative ideas. 

Ping: @martinjaggi, @tvogels

GAE Reference:
https://cloud.google.com/appengine/docs/standard/nodejs/an-overview-of-app-engine

**Comment by s314cy** [comment]
I think a reverse proxy would be doing just fine. This is easily feasible with the 'http-proxy' library (https://github.com/http-party/node-http-proxy). This would allow the server to redirect incoming URLs to internal services running on various ports. The ports would be invisible to the client/user. Adding a new task would require to edit & restart the proxy only.
